name: Publish Container
on:
  pull_request:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      tag:
        required: false
        type: string
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4
      - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
      - uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ inputs.tag != '' && format('{0}/adssmg-raspberrypi-hat:{1}', github.repository_owner, inputs.tag) || '' }}
            ${{ github.repository_owner }}/adssmg-raspberrypi-hat:latest
