name: Publish Container
on:
  pull_request:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      tag:
        required: false
        type: string
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4
      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4
      - uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ inputs.tag != '' && format('{0}/adssmg-raspberrypi-hat:{1}', github.repository_owner, inputs.tag) || '' }}
            ${{ github.repository_owner }}/adssmg-raspberrypi-hat:latest
